# Generated by Django 5.0.2 on 2024-02-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodutility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
