# Generated by Django 5.0.2 on 2024-02-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodutility', '0007_donate_money_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate_money',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='volunteer_detail',
            name='foodName',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='volunteer_detail',
            name='quantity',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='donate_money',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
