# Generated by Django 5.0.2 on 2024-02-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodutility', '0008_remove_donate_money_volunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_money',
            name='volunteer',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
