# Generated by Django 5.0.2 on 2024-02-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodutility', '0009_donate_money_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_detail',
            name='duedate',
            field=models.DateField(default='2003-12-11'),
        ),
    ]
