# Generated by Django 5.0.2 on 2024-02-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodutility', '0010_volunteer_detail_duedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate_Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(blank=True, max_length=122, null=True)),
                ('volunteer', models.CharField(blank=True, max_length=122, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
