# Generated by Django 5.0.2 on 2024-02-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodutility', '0011_donate_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_food',
            name='foodName',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='donate_food',
            name='quantity',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
